### ISSUE TITLE
Keep your files in your in here

### ISSUE THREAD

**Issue by Ma1hT3ach3r** [AYJACKSON-ICS4U/20time-log-due-every-saturday-night-awebs#1]
Alex,

Not that you have to but I think people would like to see what you have made so far.

Using pictures, keeping files, using the projects and wiki tab can allow you to keep all your progress in a place that allows for deployability...

I think we (the whole class) needs to get more familiar with the power and possibilities that Git/GitHub have to offer...

**Comment by awebsters** [comment]
pictures are in the readme.md for each week progress is made to the code. The code is in the repo and the beginnings of a project page and wiki have begun.
